#!/bin/bash

# hosts src
url_list=(
  "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
  "https://raw.githubusercontent.com/AdAway/adaway.github.io/master/hosts.txt"
  "https://www.malwaredomainlist.com/hostslist/hosts.txt"
)

host_files=()

# reset /etc/hosts
echo -e "127.0.0.1 localhost\n127.0.0.1 darkhole\n# The following lines are desirable for IPv6 capable hosts\n::1 ip6-localhost ip6-loopback\nfe00::0 ip6-localnet\nff00::0 ip6-mcastprefix\nff02::1 ip6-allnodes\nff02::2 ip6-allrouters\nff02::3 ip6-allhosts" > /tmp/defaulthosts

# downloading hosts……
echo "downloading hosts to /tmp"

for url in ${url_list[@]}
do
  hostfile=$(mktemp /tmp/adhosts.XXXXX)
  echo "downloading hosts file from $url to $hostfile"
  curl -#C - -o $hostfile "$url"
  host_files+=($hostfile)
done

# edit hosts file
echo "edit hosts"
sudo -S sed -i '/localhost/d' ${host_files[@]}
sudo -S sed -i '/ip6-localhost/d' ${host_files[@]}
sudo -S sed -i '/127.0.0.1 local/d' ${host_files[@]}
sudo -S sed -i '/255.255.255.255 broadcasthost/d' ${host_files[@]}
sudo -S sed -i '/0.0.0.0 0.0.0.0/d' ${host_files[@]}

echo "merge hosts"
sudo -S cat /tmp/defaulthosts ${host_files[@]} >> /tmp/hosts

echo "copy hosts to /etc/hosts"
sudo -S cp /tmp/hosts /etc/hosts

echo "removing temp files"
sudo -S rm -fv /tmp/defaulthosts ${host_files[@]} /tmp/hosts

echo "Done!"
